
--CREATE VIEW DbUsers AS SELECT DISTINCT GRANTEE AS User, GRANTEDROLE AS Role FROM INFORMATION_SCHEMA.Rights WHERE GRANTEETYPE = 'USER';

--CREATE VIEW DbUsers AS SELECT DISTINCT GRANTEE AS User, GROUP_CONCAT(GRANTEDROLE) AS Roles FROM INFORMATION_SCHEMA.Rights WHERE GRANTEETYPE = 'USER' GROUP BY GRANTEE;

CREATE VIEW DbUsers AS SELECT DISTINCT Users.Name AS User, GROUP_CONCAT(Rights.GrantedRole) AS Roles FROM INFORMATION_SCHEMA.Users LEFT OUTER JOIN INFORMATION_SCHEMA.Rights ON Users.Name = Rights.Grantee WHERE Rights.Grantee IS NULL OR GranteeType = 'USER' GROUP BY Users.Name