
--CREATE VIEW DbUsers AS SELECT DISTINCT GRANTEE AS User, GRANTEDROLE AS Role FROM INFORMATION_SCHEMA.Rights WHERE GRANTEETYPE = 'USER';

CREATE VIEW DbUsers AS SELECT DISTINCT GRANTEE AS User, GROUP_CONCAT(GRANTEDROLE) AS Roles FROM INFORMATION_SCHEMA.Rights WHERE GRANTEETYPE = 'USER' GROUP BY GRANTEE;