

-- TODO: change the order of the tables

CREATE SCHEMA ART;

DROP TABLE ART.AUTHCONDITIONS;

CREATE CACHED TABLE ART.AUTHCONDITIONS
(
   ID                  INTEGER      NOT NULL,
   TYPE                VARCHAR(7),
   PATTERNCONDITIONID  INTEGER,
   PROFILECONDITIONID  INTEGER
);

ALTER TABLE ART.AUTHCONDITIONS
   ADD PRIMARY KEY (ID);

ALTER TABLE AUTHCONDITIONS
  ADD CONSTRAINT FKBY0FHRI2ADU7X4TACDB5XXTOR FOREIGN KEY (PATTERNCONDITIONID)
  REFERENCES ART.AUTHPATTERNCONDITIONS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

ALTER TABLE AUTHCONDITIONS
  ADD CONSTRAINT FKRFFKS0L01MIQB7TBS4HRQH108 FOREIGN KEY (PROFILECONDITIONID)
  REFERENCES ART.AUTHPROFILECONDITIONS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

CREATE INDEX ART.FKRFFKS0L01MIQB7TBS4HRQH108_INDEX_D
   ON ART.AUTHCONDITIONS (PROFILECONDITIONID ASC);

CREATE INDEX ART.FKBY0FHRI2ADU7X4TACDB5XXTOR_INDEX_D
   ON ART.AUTHCONDITIONS (PATTERNCONDITIONID ASC);

DROP TABLE ART.AUTHPATTERNCONDITIONPROPERTIES;

CREATE CACHED TABLE ART.AUTHPATTERNCONDITIONPROPERTIES
(
   ID                  INTEGER        NOT NULL,
   AUTHOBJECT          VARCHAR(255),
   AUTHOBJECTPROPERTY  VARCHAR(255),
   VALUE1              VARCHAR(255),
   VALUE2              VARCHAR(255),
   VALUE3              VARCHAR(255),
   VALUE4              VARCHAR(255),
   CONDITIONID         INTEGER
);

ALTER TABLE ART.AUTHPATTERNCONDITIONPROPERTIES
   ADD PRIMARY KEY (ID);

ALTER TABLE AUTHPATTERNCONDITIONPROPERTIES
  ADD CONSTRAINT FKDE80IWXUOSWJFYHM5UOOTOAF7 FOREIGN KEY (CONDITIONID)
  REFERENCES ART.AUTHPATTERNCONDITIONS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

CREATE INDEX ART.FKDE80IWXUOSWJFYHM5UOOTOAF7_INDEX_7
   ON ART.AUTHPATTERNCONDITIONPROPERTIES (CONDITIONID ASC);

DROP TABLE ART.AUTHPATTERNCONDITIONS;

CREATE CACHED TABLE ART.AUTHPATTERNCONDITIONS
(
   ID  INTEGER   NOT NULL
);

ALTER TABLE ART.AUTHPATTERNCONDITIONS
   ADD PRIMARY KEY (ID);

DROP TABLE ART.AUTHPATTERNS;

CREATE CACHED TABLE ART.AUTHPATTERNS
(
   ID           INTEGER        NOT NULL,
   DESCRIPTION  VARCHAR(255),
   LINKAGE      VARCHAR(4),
   USECASEID    VARCHAR(255)
);

ALTER TABLE ART.AUTHPATTERNS
   ADD PRIMARY KEY (ID);

  DROP TABLE ART.AUTHPROFILECONDITIONS;

CREATE CACHED TABLE ART.AUTHPROFILECONDITIONS
(
   ID       INTEGER        NOT NULL,
   PROFILE  VARCHAR(255)
);

ALTER TABLE ART.AUTHPROFILECONDITIONS
   ADD PRIMARY KEY (ID);

DROP TABLE ART.CONFIGURATIONS;

CREATE CACHED TABLE ART.CONFIGURATIONS
(
   ID           INTEGER        NOT NULL,
   DESCRIPTION  VARCHAR(255),
   NAME         VARCHAR(255),
   WHITELISTID  INTEGER
);

ALTER TABLE ART.CONFIGURATIONS
   ADD PRIMARY KEY (ID);

ALTER TABLE CONFIGURATIONS
  ADD CONSTRAINT FKSCFOM43OHPIW8YRBEVGVUWWSN FOREIGN KEY (WHITELISTID)
  REFERENCES ART.WHITELISTS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

CREATE INDEX ART.FKSCFOM43OHPIW8YRBEVGVUWWSN_INDEX_7
   ON ART.CONFIGURATIONS (WHITELISTID ASC);

DROP TABLE ART.NM_AUTHPATTERN_AUTHCONDITION;

CREATE CACHED TABLE ART.NM_AUTHPATTERN_AUTHCONDITION
(
   ID             INTEGER   NOT NULL,
   CONDITIONID    INTEGER,
   AUTHPATTERNID  INTEGER
);

ALTER TABLE ART.NM_AUTHPATTERN_AUTHCONDITION
   ADD PRIMARY KEY (ID);

ALTER TABLE NM_AUTHPATTERN_AUTHCONDITION
  ADD CONSTRAINT FKIEPG5AXWXEV3DS6ARJLBU27W4 FOREIGN KEY (CONDITIONID)
  REFERENCES ART.AUTHPATTERNCONDITIONS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

ALTER TABLE NM_AUTHPATTERN_AUTHCONDITION
  ADD CONSTRAINT FKDK9G7PY585TV02LILKS8XYYH5 FOREIGN KEY (AUTHPATTERNID)
  REFERENCES ART.AUTHPATTERNS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

CREATE INDEX ART.FKIEPG5AXWXEV3DS6ARJLBU27W4_INDEX_C
   ON ART.NM_AUTHPATTERN_AUTHCONDITION (CONDITIONID ASC);

CREATE INDEX ART.FKDK9G7PY585TV02LILKS8XYYH5_INDEX_C
   ON ART.NM_AUTHPATTERN_AUTHCONDITION (AUTHPATTERNID ASC);

DROP TABLE ART.NM_CONFIGURATION_AUTHPATTERN;

CREATE CACHED TABLE ART.NM_CONFIGURATION_AUTHPATTERN
(
   ID             INTEGER   NOT NULL,
   CONFIGID       INTEGER,
   AUTHPATTERNID  INTEGER
);

ALTER TABLE ART.NM_CONFIGURATION_AUTHPATTERN
   ADD PRIMARY KEY (ID);

ALTER TABLE NM_CONFIGURATION_AUTHPATTERN
  ADD CONSTRAINT FKGJR157U6KHFD84XETQB432HYV FOREIGN KEY (AUTHPATTERNID)
  REFERENCES ART.AUTHPATTERNS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

ALTER TABLE NM_CONFIGURATION_AUTHPATTERN
  ADD CONSTRAINT FKI8QT7VQM47W1J5C7F5SHVSTAQ FOREIGN KEY (CONFIGID)
  REFERENCES ART.CONFIGURATIONS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

CREATE INDEX ART.FKGJR157U6KHFD84XETQB432HYV_INDEX_4
   ON ART.NM_CONFIGURATION_AUTHPATTERN (AUTHPATTERNID ASC);

CREATE INDEX ART.FKI8QT7VQM47W1J5C7F5SHVSTAQ_INDEX_4
   ON ART.NM_CONFIGURATION_AUTHPATTERN (CONFIGID ASC);

DROP TABLE ART.WHITELISTENTRIES;

CREATE CACHED TABLE ART.WHITELISTENTRIES
(
   ID           INTEGER        NOT NULL,
   USECASEID    VARCHAR(255),
   USERNAME     VARCHAR(255),
   WHITELISTID  INTEGER
);

ALTER TABLE ART.WHITELISTENTRIES
   ADD PRIMARY KEY (ID);

ALTER TABLE WHITELISTENTRIES
  ADD CONSTRAINT FKE75RDPSJFU7KPPO53HR67H2FX FOREIGN KEY (WHITELISTID)
  REFERENCES ART.WHITELISTS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

CREATE INDEX ART.FKE75RDPSJFU7KPPO53HR67H2FX_INDEX_7
   ON ART.WHITELISTENTRIES (WHITELISTID ASC);

DROP TABLE ART.WHITELISTS;

CREATE CACHED TABLE ART.WHITELISTS
(
   ID           INTEGER        NOT NULL,
   DESCRIPTION  VARCHAR(255)
);

ALTER TABLE ART.WHITELISTS
   ADD PRIMARY KEY (ID);
